### ISSUE TITLE
Complètement soûl

### ISSUE THREAD

**Issue by Ealhad** [BuonOmo/belloc#1]
Non mais oh

**Comment by BuonOmo** [comment]
Oui ?

**Comment by Ealhad** [comment]
Blague à part, tu devrais arrêter d'utiliser systématiquement jQuery. Ça sert [plus à grand chose](http://youmightnotneedjquery.com/) aujourd'hui, et il y a des bibliothêques bien plus [intéressantes](http://vuejs.org/).

**Comment by BuonOmo** [comment]
Merci pour les petits liens, de toutes façons quant tu utilise angular, jquery n’est plus très utile ! Mais la je t’avoue que c’était une solution de facilité pour développer ça en 20 mn ! Il n’en tient qu’a toi de m’envoyer une PR utilisant un autre framework ou du js pure :)

**Comment by Ealhad** [comment]
J'aime pas Angular (c'est bien pour des gros trucs à mon avis, plusieurs dizaines de devs), en revanche Vue.js est extra !

**Comment by BuonOmo** [comment]
Il a l’air sympa, j’ai un petit dev à faire pour ma coloc actuelle, je 
vais tester !

**Comment by BuonOmo** [comment]
Mais vue.js c’est pas du MVC ? J’ai l’impression que les services et les contrôleurs sont complètement mélangés

**Comment by Ealhad** [comment]
[MVVM](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel)

**Comment by BuonOmo** [comment]
J’ai testé angular 2 avec typescript, c’est correct, même pour des petits projets!

**Comment by Ealhad** [comment]
Soit.
